---
- name: Module1 setup
  hosts: all
  roles:
    # -------------------------   Base   -------------------------
    - name: Basic Setup
      role: base
      tags: ["base"]
      become: true
    # -------------------------  Docker  -------------------------
    - name: Install Docker Engine
      role: docker-engine
      tags: ["docker-engine"]
      become: true
    - name: Setup Docker Swarm
      role: docker-swarm
      tags: ["docker-swarm"]
      become: true

    # -------------------------          -------------------------
