---
- name: Basic setup of {{ ansible_distribution }}
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Users
  import_tasks: users.yml

# ------------------ Slack Notification
- slack: token={{ secrets.slack.token }} color="good" msg="Deployment of *Base role* on \"*{{ inventory_hostname }}*\" node is finished"
  become: no
  delegate_to: localhost
  when: not slack_mute
