---
#- apt_key: id=0C49F3730359A14518585931BC711F9BA15703C6 keyserver=keyserver.ubuntu.com state=present
#- apt_repository: repo="deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" state=present filename='mongodb-org'

- name: Ensure common packages are installed
  apt: name={{ item }} state=present
  loop:
    - apache2-utils               # Apache HTTP Server (utility programs for web servers)
    - alien                       # convert and install rpm and other packages
    - aptitude                    # aptitude is an Ncurses based FrontEnd to Apt
    - bash-completion             # programmable completion functions for bash
    - bridge-utils                # Utilities for configuring the Linux Ethernet bridge
    - curl                        # command line tool for transferring data with URL syntax
    - ethtool                     # display or change Ethernet device setting
    - git                         # fast, scalable, distributed revision control system
    - htop                        # interactive processes viewer
    - iotop                       # simple top-like I/O monitor
    - iperf                       # Internet Protocol bandwidth measuring tool
    - iptstate                    # top-like interface to your netfilter connection-tracking table
    - irqbalance                  # daemon to balance interrupts for SMP systems
    - jq                          # lightweight and flexible command-line JSON processor
    - mc                          # Midnight Commander - a powerful file manager
    - mlocate                     # quickly find files on the filesystem based on their name
    - mtr                         # Full screen ncurses and X11 traceroute tool
    - ncdu                        # Ncurses disk usage viewer
    - pv                          # Shell pipeline element to meter data passing through
    - python-setuptools           # Easily build and distribute Python packages
    - rsync                       # fast, versatile, remote (and local) file-copying tool
    - software-properties-common  # manage the repositories that you install software from
    - sysfsutils                  # sysfs query tool and boot-time setup
    - sysstat                     # system performance tools for Linux
    - telnet                      # basic telnet client
    - tcpdump                     # command-line network traffic analyzer
    - tmux                        # terminal multiplexer
    - traceroute                  # Traces the route taken by packets over an IPv4/IPv6 network
    - tree                        # displays an indented directory tree, in color
    - vim                         # Vi IMproved - enhanced vi editor
    - wget                        # retrieves files from the web

- name: Install pip
  easy_install: name=pip
