---
docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377
docker_swarm_network: 172.30.31.0/24
docker_swarm_network_name: swarm-net

docker_admin_users:
  - divanov
